# Generated by Django 5.1.2 on 2024-10-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='accesslevels',
            name='access_type',
        ),
        migrations.AddField(
            model_name='accesslevels',
            name='role',
            field=models.CharField(blank=True, choices=[('Администратор', 'Администратор'), ('Менеджер', 'Менеджер'), ('Склад', 'Склад'), ('Закупка', 'Закупка'), ('ИТР/Планировщик', 'ИТР/Планировщик')], max_length=50, null=True, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='access_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.accesslevels', verbose_name='Уровень доступа'),
        ),
    ]
