# Generated by Django 5.1.2 on 2024-10-24 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_category_name_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequest',
            old_name='purchase_date',
            new_name='request_date',
        ),
        migrations.AlterField(
            model_name='employees',
            name='access_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.accesslevels', verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото/скриншот'),
        ),
    ]
