# Generated by Django 5.1.2 on 2024-11-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_departments_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='productrequest',
            options={'verbose_name': 'заявку на закуп', 'verbose_name_plural': 'Заявки на закуп'},
        ),
    ]
