# Generated by Django 5.1.2 on 2024-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_purchase_date_productrequest_request_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPivotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'позицию',
                'verbose_name_plural': 'NEW Сводная таблица',
            },
        ),
        migrations.AlterModelOptions(
            name='pivottable',
            options={'verbose_name': 'позицию', 'verbose_name_plural': 'Сводная таблица'},
        ),
        migrations.AlterModelOptions(
            name='storagecells',
            options={'verbose_name': 'адресную ячейку', 'verbose_name_plural': 'адресные ячейки'},
        ),
    ]
