# Generated by Django 5.1.2 on 2024-11-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_categories_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'отдел/цех', 'verbose_name_plural': 'Подразделения компании'},
        ),
        migrations.AlterModelOptions(
            name='modelcolors',
            options={'verbose_name': 'цвет заголовка', 'verbose_name_plural': 'Цвета моделей'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'поставщика', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
