# Generated by Django 5.1.2 on 2024-11-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storage', '0004_alter_departments_options_alter_modelcolors_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovies',
            name='reason_id',
        ),
        migrations.AddField(
            model_name='productmovies',
            name='reason_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('orders', 'customuser', 'projects', 'suppliers', 'productmovies')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productmovies',
            name='reason_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
