# Generated by Django 5.1.2 on 2024-10-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_newpivottable_alter_pivottable_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPivotTable',
        ),
    ]
