# Generated by Django 5.1.2 on 2024-11-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_productmovies_reason_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovies',
            name='reason_content_type',
        ),
        migrations.RemoveField(
            model_name='productmovies',
            name='reason_object_id',
        ),
        migrations.AddField(
            model_name='productmovies',
            name='reason_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID источника перемещения'),
        ),
    ]
