# Generated by Django 5.1.2 on 2024-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_productmovies_reason_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категорию / признак', 'verbose_name_plural': 'Категории, признаки, свойства'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(blank=True, to='storage.categories', verbose_name='Категория / признак'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Категория/признак'),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='reason_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='return_to_supplier_reason',
            field=models.CharField(blank=True, choices=[('Несоответствие заказу', 'Несоответствие заказу'), ('Дефекты материалов', 'Дефекты материалов'), ('Дефекты изделий', 'Дефекты изделий'), ('Излишек', 'Излишек'), ('Нарушение сроков поставки', 'Нарушение сроков поставки')], max_length=50, null=True, verbose_name='Причина'),
        ),
    ]
