# Generated by Django 5.1.2 on 2024-11-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_categories_options_remove_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='department',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modelcolors',
            old_name='model_name',
            new_name='name',
        ),
    ]
