# Generated by Django 5.1.2 on 2024-11-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_rename_department_departments_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagecells',
            old_name='cell_address',
            new_name='name',
        ),
    ]
