# Generated by Django 5.1.2 on 2024-11-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_rename_cell_address_storagecells_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.productrequest', verbose_name='Заявка на закуп'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.orders', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='product_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.productmovies', verbose_name='Перемещение по складу'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.products', verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='product_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.productrequest', verbose_name='Заявка на закуп'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='new_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storagecells', verbose_name='Адрес ячейки'),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.products', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.products', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.projects', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.suppliers', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_engineer_set', to=settings.AUTH_USER_MODEL, verbose_name='Инженер'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
