# Generated by Django 5.1.2 on 2024-11-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_customuser_department_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequest',
            old_name='_old',
            new_name='project_old',
        ),
    ]
