version: '3.8'

services:
  db:
    image: postgres:15
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gjcnu_1827
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: warehouse_app
    command: gunicorn warehouse.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:gjcnu_1827@db:5432/warehouse_db
      DEBUG: "True"

volumes:
  db_data:
  static_volume:
